apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: certmanager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${acmeEmail}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
            - "${domain}"
      dns01:
        route53:
          region: ${region}
          hostedZoneID: ${hostedZoneId}
          accessKeyID: ${accessKey}
          secretAccessKeySecretRef:
            name: aws-iam
            key: secret_access_key